CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  password VARCHAR(32) NOT NULL,
  name VARCHAR(16) NOT NULL,
  mail VARCHAR(32) NOT NULL UNIQUE,
  introduce TEXT NOT NULL DEFAULT '欢迎关注youtube频道：Kristy Zhou',
  isActive CHAR(1) NOT NULL DEFAULT '0',
  gender INTEGER NOT NULL DEFAULT 0,
  face VARCHAR(64),
  isAdmin CHAR(1) NOT NULL default '0'
);

CREATE TABLE class (
  id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE article (
  class_id INTEGER PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  content TEXT NOT NULL,
  author INTEGER NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(author) REFERENCES user(id),
  FOREIGN KEY(class_id) REFERENCES class(id)
);

CREATE TABLE comment (
  class_id INTEGER PRIMARY KEY,
  content VARCHAR(256) NOT NULL,
  author INTEGER NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(author) REFERENCES user(id),
  FOREIGN KEY(class_id) REFERENCES class(id)
);